version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/WordPress
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: echo "Install finished"
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: appStart.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: echo "kill"
      timeout: 300
      runas: root